# Docker compose file  for a single elasticsearch node
# 
# Elastic Search Consumes a decent amount of memory so be aware
# of that.
#
# Ensure kibana and elasticsearch have the same version
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    ports:
      - 5601:5601"
volumes:
  esdata1:
    driver: local

