# Docker compose file  for a single postgres instance

version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres # Name of superuser
      POSTGRES_PASSWORD: password # Password of superuser
      POSTGRES_DB: database # Database to be automatically created
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
    driver: local
