# Docker compose file  for a single postgis instance
version: "3"
services:
  postgis:
    image: kartoza/postgis:11.5-2.8
    container_name: postgis-tkm
    volumes:
      - "postgis-data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
volumes:
  postgis-data:
    driver: local
